name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      VERSION: 0.0.2
    
    steps:
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.0-beta2
      with:
        format: "${major}.${minor}.${patch}"
        change_path: "semantic-versions"
      id: version

     
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "NEW SEMANTIC VERSION: $NEW_VERSION"


