name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      VERSION: 0.0.0

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: | 
        docker login -u klerith -p ${{ secrets.DOCKERPASSWORD }}
        docker build . --file Dockerfile --tag klerith/nest-graphql-dev:${{fromJson(steps.set_var.outputs.packageJson).version}}
        docker push klerith/nest-graphql-dev:${{fromJson(steps.set_var.outputs.packageJson).version}}
