name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
       
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease-${increment}"
      id: version

     
#    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "NEW SEMANTIC VERSION: $NEW_VERSION!!"

    - name: Build image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: | 
        docker build . --file Dockerfile --tag klerith/nest-graphql-dev:$NEW_VERSION
        docker build . --file Dockerfile --tag klerith/nest-graphql-dev:latest

    - name: Push the Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: | 
        docker push klerith/nest-graphql-dev:$VERSION
        docker push klerith/nest-graphql-dev:latest


