name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      VERSION: 0.0.1

    steps:
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.0-beta2

    
    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: | 
        docker login -u klerith -p ${{ secrets.DOCKERPASSWORD }}
        docker build . --file Dockerfile --tag klerith/nest-graphql-dev:$VERSION
        docker push klerith/nest-graphql-dev:$VERSION
