name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      VERSION: 0.0.2
    
    steps:
#     - uses: PaulHatch/semantic-version@v5.0.0-beta2
#       with:
#         format: "${major}.${minor}.${patch}"
#     - id: version
#     - name: Git Semantic Version
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - uses: actions/checkout@v3
    - name: Build image
      run: | 
        docker build . --file Dockerfile --tag klerith/nest-graphql-dev:$VERSION

    - uses: actions/checkout@v3
    - name: Push the Docker image
      run: | 
        docker push klerith/nest-graphql-dev:$VERSION
